blank_issues_enabled: false
contact_links:
  - name: Zgłoszenie bezpieczeństwa
    url: https://github.com/wcagcms/placowka-online/security/advisories/new
    about: Nie publikuj podatności ani sekretów w Issue.
